FROM raspbian/stretch

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install make
RUN apt-get -y install gcc


RUN apt-get -y install python-setuptools
RUN easy_install pip
RUN apt-get -y install python-dev
RUN apt-get -y install libpcre3-dev


RUN git clone git://git.drogon.net/wiringPi
RUN cd wiringPi/ && ./build && cd .. && rm -rf wiringPi
RUN apt-get -y install wiringpi

RUN apt-get -y install RPI.GPIO

RUN apt-get -y install i2c-tools
RUN apt-get -y install python-smbus

VOLUME ["/data/brewing-controller"]

# Define working directory
WORKDIR /data/brewing-controller


# Define default command
CMD  ["bin/sh"]

## to run : docker run -d -p 5000:5000 --privileged --cap-add SYS_RAWIO --device /dev/mem --restart unless-stopped -v /data/brewing-controller --name test xavfan/brewing controller




